export const response = {
  organization: {
    name: 'Safe Fleet',
    login: 'safe-fleet',
    repositories: {
      nodes: [
        {
          name: 'media-management-ui-temp',
          description: null,
          deleteBranchOnMerge: true,
          hasIssuesEnabled: true,
          hasProjectsEnabled: false,
          hasWikiEnabled: true,
          isPrivate: true,
          isTemplate: false,
          mergeCommitAllowed: true,
          pushedAt: '2020-02-24T17:24:44Z',
          rebaseMergeAllowed: true,
          squashMergeAllowed: true,
          viewerPermission: 'ADMIN',
          fundingLinks: [],
          licenseInfo: null,
          masterCodeOwner: { text: '@alejo345\n' },
          developCodeOwner: { text: '@alejo345\n' },
          dependencyGraphManifests: {
            nodes: [
              {
                id:
                  'MDIzOkRlcGVuZGVuY3lHcmFwaE1hbmlmZXN0MjM0MTY0NDAzOjE0MTY3MzAzMQ==',
              },
            ],
          },
          defaultBranchRef: { name: 'develop' },
          collaborators: {
            edges: [{ permission: 'ADMIN', node: { login: 'aramirezh-dev' } }],
          },
          branchProtectionRules: {
            nodes: [
              {
                pattern: 'master',
                isAdminEnforced: true,
                requiresApprovingReviews: true,
                requiredApprovingReviewCount: 2,
                requiredStatusCheckContexts: [
                  'continuous-integration/jenkins/branch',
                ],
                requiresCodeOwnerReviews: true,
                requiresCommitSignatures: true,
                requiresStatusChecks: true,
                requiresStrictStatusChecks: true,
                restrictsPushes: true,
                restrictsReviewDismissals: false,
                dismissesStaleReviews: true,
                pushAllowances: { nodes: [] },
              },
              {
                pattern: 'develop',
                isAdminEnforced: true,
                requiresApprovingReviews: true,
                requiredApprovingReviewCount: 1,
                requiredStatusCheckContexts: [
                  'continuous-integration/jenkins/branch',
                ],
                requiresCodeOwnerReviews: true,
                requiresCommitSignatures: true,
                requiresStatusChecks: true,
                requiresStrictStatusChecks: true,
                restrictsPushes: true,
                restrictsReviewDismissals: false,
                dismissesStaleReviews: true,
                pushAllowances: { nodes: [] },
              },
              {
                pattern: 'release/*',
                isAdminEnforced: true,
                requiresApprovingReviews: true,
                requiredApprovingReviewCount: 1,
                requiredStatusCheckContexts: [
                  'continuous-integration/jenkins/branch',
                ],
                requiresCodeOwnerReviews: true,
                requiresCommitSignatures: true,
                requiresStatusChecks: true,
                requiresStrictStatusChecks: true,
                restrictsPushes: true,
                restrictsReviewDismissals: false,
                dismissesStaleReviews: true,
                pushAllowances: { nodes: [] },
              },
              {
                pattern: 'hotfix/*',
                isAdminEnforced: true,
                requiresApprovingReviews: true,
                requiredApprovingReviewCount: 1,
                requiredStatusCheckContexts: [
                  'continuous-integration/jenkins/branch',
                ],
                requiresCodeOwnerReviews: true,
                requiresCommitSignatures: true,
                requiresStatusChecks: true,
                requiresStrictStatusChecks: true,
                restrictsPushes: true,
                restrictsReviewDismissals: false,
                dismissesStaleReviews: true,
                pushAllowances: { nodes: [] },
              },
              {
                pattern: '**/**',
                isAdminEnforced: true,
                requiresApprovingReviews: false,
                requiredApprovingReviewCount: null,
                requiredStatusCheckContexts: [],
                requiresCodeOwnerReviews: false,
                requiresCommitSignatures: true,
                requiresStatusChecks: false,
                requiresStrictStatusChecks: true,
                restrictsPushes: false,
                restrictsReviewDismissals: false,
                dismissesStaleReviews: false,
                pushAllowances: { nodes: [] },
              },
              {
                pattern: 'test',
                isAdminEnforced: true,
                requiresApprovingReviews: false,
                requiredApprovingReviewCount: null,
                requiredStatusCheckContexts: [],
                requiresCodeOwnerReviews: false,
                requiresCommitSignatures: true,
                requiresStatusChecks: false,
                requiresStrictStatusChecks: true,
                restrictsPushes: false,
                restrictsReviewDismissals: false,
                dismissesStaleReviews: false,
                pushAllowances: { nodes: [] },
              },
            ],
          },
          refs: {
            nodes: [
              {
                name: 'badge-jenkins',
                target: { committedDate: '2020-01-21T22:53:43Z' },
              },
              {
                name: 'develop',
                target: { committedDate: '2020-02-24T16:52:34Z' },
              },
              {
                name: 'feature/cc-128-whatever',
                target: { committedDate: '2020-02-24T16:52:34Z' },
              },
              {
                name: 'feature/whatever/mm-123',
                target: { committedDate: '2020-02-24T16:52:34Z' },
              },
              {
                name: 'master',
                target: { committedDate: '2020-01-22T14:54:00Z' },
              },
              {
                name: 'release/1.2.2',
                target: { committedDate: '2020-02-24T16:52:34Z' },
              },
            ],
          },
        },
      ],
    },
  },
};
